default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 8Makawa8
  host: localhost

development:
  <<: *default
  database: nomikaisan_development

test:
  <<: *default
  database: nomikaisan_test

production:
  <<: *default
  database: nomikaisan_production
  username: root
  password: 8Makawa8
