default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 0Y4BfYkzJdac9ZLTl0jh
  host: nomikaisan-db.cbow2w4wi3hv.ap-northeast-1.rds.amazonaws.com
  port: 3306

development:
  <<: *default
  database: nomikaisan_development

test:
  <<: *default
  database: nomikaisan_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>
  port: 3306
